# Compose a postgres database together with the extension pgvector
services:
  db:
    hostname: db
    # image: ankane/pgvector:latest
    image: ankane/pgvector:v0.5.1
    container_name: local_pgdb

    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: testuser@elta.com
      PGADMIN_DEFAULT_PASSWORD: testpwd
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
